### ISSUE TITLE
Archived on CRAN

### ISSUE THREAD

**Issue by traversc** [MullinsLab/r-scriptName#2]
Any chance of getting it back on?

**Comment by tsibley** [comment]
Hi @traversc, thanks for your interest in getting this back on CRAN! The first step is to address issue #1 and make sure tests and CRAN checks pass (`make test check cran-check`). Would you be willing to do that and submit a PR?

Once that's done, the next step is for someone (you? me? someone from @MullinsLab, maybe @silby?) to start the CRAN submission process for a new version.

**Comment by traversc** [comment]
I sent a pull request, seemed like a quick enough fix.  I can go with re-submitting if you'd like.

**Comment by traversc** [comment]
Hi @tsibley @MullinsLab @silby, I'm sure you all are busy.  Is there any issue with me forking and re-submitting to CRAN?

**Comment by tsibley** [comment]
Thanks for the fix! I applied it to master on this repo.

For CRAN submission to be successful, I think the deprecation of `rlang::ctxt_stack()` will need to be addressed too. This was described in #1 as:

> Also, be advised that `rlang::ctxt_stack()` has been soft-deprecated in rlang 0.3.0. Please use `base::sys.calls()` instead.

I think some munging of the `base::sys.calls()` return values will be necessary since it includes more than the function name.

**Comment by traversc** [comment]
Okay, I switched it over to use `sys.calls`.  It still uses some `rlang` but not anything deprecated.  

Please check the latest commit in the pull request.

**Comment by tsibley** [comment]
Thanks @traversc for keeping on this! I've cherry-picked your commit into master, added you as a contributor in DESCRIPTION, and resubmitted to CRAN as 1.0.1
